# tokenstore datasource
token:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sharewood_tokens
    username: tomcatUser
    password: password1234
    jpa:
      hibernate:
        naming: 
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# photos datasource
photo:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sharewood_photos
    username: tomcatUser
    password: password1234


  
spring:
  servlet: 
    multipart: 
      max-file-size: 10MB
      max-request-size: 10MB

server: 
  port: 8081


security:
  oauth2:
    resource:
      id: SHAREWOOD

# change to match your own filesystem 
photos:
  baseDirPath: /home/dominique/sharewood-reloaded-regression/photos/




  
