server:
  port: 8080
 
usersResourceUriBase: http://localhost:9090/user/

gateway-path: /authorization 

gateway-url: http://localhost:5555/authorization

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/  
      
      
spring:
  jpa:
    database: "MYSQL"
    show-sql: "true"
   
  datasource:
    platform: mysql
    url: "jdbc:mysql://localhost:3306/sharewood_tokens"
    username: dbuser
    password: password1234
      
  session:
    store-type: redis  
