# tokenstore database
myauthorization:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sharewood_tokens
    username: dbuser
    password: password1234
  jpa:
    hibernate:
      naming: 
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl



# photos database
photo: 
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sharewood_photos
    username: dbuser
    password: password1234


server:
  port: 8081


spring:
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

security:
  oauth2:
    resource: 
      id: SHAREWOOD
      filter-order: 3

photos:
  baseDirPath: /home/dominique/workspace-sharewood-reloaded-resource/photos/






