server:
  port: 5555
    
zuul:
  sensitive-headers: 
  routes:  
  
    sharewood-by-address:
      path: /sharewood-by-address/**
      url: http://localhost:8081/
    sharewood-by-service:
      path: /sharewood-by-service/**
      serviceId: sharewood-server
    sharewood-server: /sharewood/**   
    
    authorization-by-address:
      path: /authorization-by-address/**
      url: http://localhost:8080/
    authorization-by-service:
      path: /authorization-by-service/**
      serviceId: authorization
    authorization: /authorization/**   
    
spring:
  session:
    store-type: redis
        
     
     
