server:
  port: 8888

spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native: 
          searchLocations: 
            # edit this line to match your own filesystem
            file:///home/dominique/sharewood-reloaded/config-repo
         
